CREATE DATABASE Senai_Vagas;
GO

USE Senai_Vagas;
GO

CREATE TABLE TipoUsuario (
	IdTipoUsuario	INT PRIMARY KEY IDENTITY
	,TituloTipoUsuario	VARCHAR(255) NOT NULL UNIQUE 
);
GO

CREATE TABLE Cursos (
	IdCursos	INT PRIMARY KEY IDENTITY 
	,IdTituloCursos	VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE Enderecos (
	IdEndereco	INT PRIMARY KEY IDENTITY 
	,Cep		CHAR(8) NOT NULL
	,Logradouro	VARCHAR(255) NOT NULL
	,Complemento	VARCHAR(255)
	,Bairro		VARCHAR(255) NOT NULL
	,Uf			VARCHAR(255) NOT NULL
	,Cidade		VARCHAR(255) NOT NULL
	,Numero		INT NOT NULL
);
GO 

CREATE TABLE PerfilComportamental (
	IdPerfilComportamental	INT PRIMARY KEY IDENTITY
	,TituloPerfilComportamental	VARCHAR(255) NOT NULL UNIQUE
);
GO 

CREATE TABLE Situacao (
	IdSituacao	INT PRIMARY KEY IDENTITY
	,TituloSituacao	VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE Dicas (
	IdDica	INT PRIMARY KEY IDENTITY 
	,TituloDica	VARCHAR(255) NOT NULL
	,Descricao	TEXT NOT NULL
	,Link	VARCHAR(255)
);
GO

CREATE TABLE FormaContratacao (
	IdFormaContratacao	INT PRIMARY KEY IDENTITY
	,TituloFormaContratacao	VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE Usuarios (
	IdUsuario	INT PRIMARY KEY IDENTITY
	,Email		VARCHAR(255) NOT NULL UNIQUE
	,Senha		VARCHAR(255) NOT NULL
	,FK_TipoUsuario	INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario)
);
GO

CREATE TABLE Administrador (
	IdAdministrador	INT PRIMARY KEY IDENTITY
	,Nome			VARCHAR(255) NOT NULL
	,Cpf			CHAR(11) NOT NULL UNIQUE
	,FK_Usuario		INT FOREIGN KEY REFERENCES Usuarios (IdUsuario)
);
GO

CREATE TABLE Candidatos (
	IdCandidato	INT PRIMARY KEY IDENTITY 
	,Nome		VARCHAR(255) NOT NULL
	,Sobrenome	VARCHAR(255) NOT NULL
	,Telefone	CHAR(11) NOT NULL 
	,LinkedIn	VARCHAR(255) NOT NULL UNIQUE
	,GitHub		VARCHAR(255) NOT NULL UNIQUE 
	,Apresentacao	TEXT NOT NULL 
	,Situacao	BIT DEFAULT(1) NOT NULL
	,CPF		CHAR(11) NOT NULL UNIQUE
	,Foto		VARBINARY(MAX) 
	,EmailContato	VARCHAR(255) NOT NULL 
	,IdUsuario	INT FOREIGN KEY REFERENCES Usuarios (IdUsuario)
	,FK_Curso	INT FOREIGN KEY REFERENCES Cursos (IdCursos)
	,FK_PerfilComportamental	INT FOREIGN KEY REFERENCES PerfilComportamental (IdPerfilComportamental)
	,FK_Endereco	INT FOREIGN KEY REFERENCES Enderecos (IdEndereco)
	,FK_Situacao INT FOREIGN KEY REFERENCES Situacao (IdSituacao) 
);
GO 

CREATE TABLE Empresas (
	IdEmpresa	INT PRIMARY KEY IDENTITY
	,StatusEmpresa	BIT DEFAULT(1) NOT NULL
	,RazaoSocial	VARCHAR(255) NOT NULL 
	,Cnpj			CHAR(14) NOT NULL UNIQUE 
	,Telefone		CHAR(11) NOT NULL 
	,CNAE		VARCHAR(255) NOT NULL
	,Apresentacao	TEXT NOT NULL
	,NomeResponsavel	VARCHAR(255) NOT NULL
	,CargoExercido	VARCHAR(255) NOT NULL
	/*NumeroFuncionarios	INT NOT NULL*/
	,Logo		VARBINARY(MAX) NOT NULL
	,EmailContato	VARCHAR(255) NOT NULL 
	,FK_Usuario	INT FOREIGN KEY REFERENCES Usuarios (IdUsuario)
	,FK_Endereco	INT FOREIGN KEY REFERENCES Enderecos (IdEndereco)
);
GO

CREATE TABLE Vagas (
	IdVaga	INT PRIMARY KEY IDENTITY
	,Descricao	TEXT NOT NULL 
	,Habilidades	TEXT NOT NULL
	,IdEmpresa	INT FOREIGN KEY REFERENCES Empresas (IdEmpresa) 
	,FK_FormaContratacao	INT FOREIGN KEY REFERENCES FormaContratacao (IdFormaContratacao) 
	,FK_Endereco	INT FOREIGN KEY REFERENCES Enderecos (IdEndereco)
);
GO

CREATE TABLE Inscricoes (
	IdInscricao	INT PRIMARY KEY IDENTITY 
	,StatusIncricao	BIT DEFAULT(1) NOT NULL
	,IdVaga	INT FOREIGN KEY REFERENCES Vagas (IdVaga)
	,FK_Candidato	INT FOREIGN KEY REFERENCES Candidatos (IdCandidato)
);
GO

CREATE TABLE ContratoEstagio (
	IdContratoEstagio	INT PRIMARY KEY IDENTITY
	,DataInicio	DATETIME2 NOT NULL
	,DataTermino	DATETIME2 NOT NULL
	,StatusContrato	BIT DEFAULT(1) NOT NULL
	,PlanoEstagio VARCHAR(255)
	,MotivoEvasao	VARCHAR(255) 
	,Avaliacao1	VARBINARY(MAX) NOT NULL
	,Avaliacao2	VARBINARY(MAX) NOT NULL
	,Avaliacao3	VARBINARY(MAX) NOT NULL
	,Avaliacao4	VARBINARY(MAX) NOT NULL
	,FK_Candidato	INT FOREIGN KEY REFERENCES Candidatos (IdCandidato)
	,FK_Vaga		INT FOREIGN KEY REFERENCES Vagas (IdVaga)
);
GO